- title: "Ingreso mínimo mensual vigente y referencia legal"
  publisher: "dt.gob.cl"
  date: "2026-03-07"
  url: "https://www.dt.gob.cl/portal/1628/w3-article-60141.html"
- title: "Tipos de cambio y paridades"
  publisher: "bcentral.cl"
  date: "2026-03-07"
  url: "https://www.bcentral.cl/es/web/banco-central/areas/estadisticas/tipos-de-cambios-y-paridades"
- title: "Metodología del dólar observado"
  publisher: "si3.bcentral.cl"
  date: "2026-03-07"
  url: "https://si3.bcentral.cl/estadisticas/Principal1/Metodologias/EC/PARIDADES/Dolar_observado.pdf"
- title: "NASDAQ-100 historical data"
  publisher: "nasdaq.com"
  date: "2026-03-07"
  url: "https://www.nasdaq.com/market-activity/index/ndx/historical"
- title: "Index Monthly Scorecard: December 2025"
  publisher: "nasdaq.com"
  date: "2026-03-07"
  url: "https://www.nasdaq.com/articles/index-monthly-scorecard-december-2025"
- title: "Proyecciones de población y esperanza de vida"
  publisher: "ine.gob.cl"
  date: "2026-03-07"
  url: "https://www.ine.gob.cl/estadisticas/sociales/demografia-y-vitales/proyecciones-de-poblacion"
