- title: "Comprobante de pago de remuneraciones"
  publisher: "Dirección del Trabajo"
  date: 2026-03-08
  url: "https://www.dt.gob.cl/portal/1628/w3-article-60593.html"
- title: "Anexo para comisiones, primas y tratos"
  publisher: "Dirección del Trabajo"
  date: 2026-03-08
  url: "https://www.dt.gob.cl/legislacion/1624/w3-article-60596.html"
- title: "Descuentos a la remuneración del trabajador"
  publisher: "Dirección del Trabajo"
  date: 2026-03-08
  url: "https://www.dt.gob.cl/portal/1628/w3-article-60593.html"
